# Keeper Config

# Optional: One time passcode used as client identification, allowing dynamic KSM config creation.
#keeper.client_key=

# Optional: Serves as the default KSM device auth if set.
keeper.config=

# Optional: Defaults to OS temp directory:
# Windows: %USERPROFILE%\AppData\Local\Temp\credcat_*
# Linux/Mac: /tmp/credcat_*
#keeper.files=

# Network Bind
server.host=127.0.0.1
server.port=8888
