# global level: SEVERE > WARNING > INFO > CONFIG > FINE > FINEST
.level=INFO

# package level
com.byteskeptical.keeper.level=ALL

# console output
handlers=java.util.logging.ConsoleHandler

# console configuration
java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

# one formatter to rule them all
java.util.logging.SimpleFormatter.format=%1$tF %1$tT %4$s %2$s: %5$s%6$s%n
