name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Setup Repository
        uses: actions/setup-java@v5
        with:
          cache: 'maven'
          check-latest: true
          distribution: 'temurin'
          gpg-passphrase: GPG_KEY_PASS
          gpg-private-key: ${{ secrets.GPG_KEY }}
          java-package: 'jdk'
          java-version: '21'
          server-id: central
          server-password: CENTRAL_PASSWORD
          server-username: CENTRAL_USERNAME
      - name: Publish to the Maven Central Repository
        run: mvn -B -P central -U deploy
        env:
          CENTRAL_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          CENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}
      - name: Publish to GitHub Packages
        uses: actions/setup-java@v5
        with:
          cache: 'maven'
          check-latest: true
          distribution: 'temurin'
          gpg-passphrase: GPG_KEY_PASS
          gpg-private-key: ${{ secrets.GPG_KEY }}
          java-package: 'jdk'
          java-version: '21'
          server-id: github
      - name: Publish to GitHub Packages
        run: mvn -B -U deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY_PASS: ${{ secrets.GPG_KEY_PASS }}
